name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy build files
        run: cp -R build/* ../heesuBlog/

      - name: Commit and Push Changes
        run: |
          git config --local user.email "cjmgmltn@naver.com"
          git config --local user.name "kimheesu"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push